// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  '_flex': string;
  '_grid': string;
  'align_middle': string;
  'breadcrumb': string;
  'heading30': string;
  'items_baseline': string;
  'm_auto': string;
  'margin_baseline': string;
  'ml_2': string;
  'mt-5': string;
  'mt5': string;
  'p_1': string;
  'p_2': string;
  'p_3': string;
  'pl_2': string;
  'pr_2': string;
  'px_2': string;
  'rounded_lg': string;
  'text-center': string;
  'text_slate_400': string;
  'text_slate_500': string;
  'welcomeBlock': string;
  'welcomeTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
