// Generated by Ness.js. Do not edit.
import '@nessframework/core';

declare module '@nessframework/core' {
  interface NessRouteMap {
    "/": Record<string, never>;
    "/about": Record<string, never>;
    "/server-action-demo": Record<string, never>;
  }
}
