import { createNessRequestHandler } from '@nessframework/server';

/**
 * Builds a Cloudflare Workers `fetch` handler around a Ness server build.
 *
 * Static files are served by the Workers assets binding rather than by this
 * code: the binding answers from Cloudflare's edge cache without invoking the
 * Worker at all, which is both faster and cheaper than streaming them from JS.
 *
 * Two capabilities do not exist on this runtime and are off by default:
 * on-the-fly image optimization (it needs sharp, a native module) and the
 * filesystem cache adapter. Use Cloudflare Images for the former and a
 * KV- or Durable-Object-backed cache adapter for the latter.
 */
function createWorkerHandler({
  build,
  assets = 'ASSETS',
  getLoadContext,
  ...handlerOptions
} = {}) {
  if (!build) {
    throw new TypeError(
      'createWorkerHandler requires the server build: import * as build from "./build/server/index.js".',
    );
  }

  const handler = createNessRequestHandler({
    build,
    // sharp is a native module and cannot run on Workers.
    imageHandler: undefined,
    ...handlerOptions,
  });

  return {
    async fetch(request, env, context) {
      const binding = env?.[assets];
      if (binding?.fetch) {
        const asset = await binding.fetch(request);
        if (asset.status !== 404) return asset;
      }

      // Workers hand `env` to fetch(), not to module scope, so this is the only
      // place an application can reach its bindings. Default to passing them
      // through: without it a Worker has no way to see KV, D1, or a secret.
      const loadContext = getLoadContext
        ? await getLoadContext({ request, env, context })
        : { env, ctx: context };
      return handler(request, loadContext);
    },
  };
}

const WORKER_ENTRY = `// Generated by Ness.js. Edit ness.config.mjs instead.
import * as build from '../server/index.js';
import { createWorkerHandler } from '@nessframework/deployment/cloudflare';

export default createWorkerHandler({ build });
`;

/**
 * Emits the Worker entry and a wrangler configuration that match the build
 * output layout. `nodejs_compat` is required: the framework uses
 * node:async_hooks for request-scoped caching and node:crypto for cache keys.
 */
function createWorkerConfig({
  name = 'ness-app',
  compatibilityDate = '2025-01-01',
  buildDirectory = 'build',
  main = `${buildDirectory}/worker/index.js`,
} = {}) {
  return {
    name,
    main,
    compatibility_date: compatibilityDate,
    compatibility_flags: ['nodejs_compat'],
    assets: {
      directory: `${buildDirectory}/client`,
      binding: 'ASSETS',
      // The Worker owns routing; the binding only answers for files it has.
      not_found_handling: 'none',
    },
    observability: { enabled: true },
  };
}

export { WORKER_ENTRY, createWorkerConfig, createWorkerHandler };
export default createWorkerHandler;
