import { createNessRequestHandler } from '@nessframework/server';
import { applyForwardedHeaders } from '@nessframework/server/proxy';
import { applyRuntimeConfig } from '@nessframework/server/runtime';
import type { ServerBuildLike } from '@nessframework/server';

/** The Workers static-assets binding, as much of it as this file uses. */
export interface AssetsBinding {
  fetch(request: Request): Promise<Response>;
}

export type WorkerEnv = Record<string, unknown> & {
  [binding: string]: unknown;
};

export interface WorkerLoadContextArgs {
  request: Request;
  env: WorkerEnv | undefined;
  context: unknown;
}

export interface WorkerHandlerOptions {
  build?: unknown;
  /** Name of the static-assets binding. Defaults to `ASSETS`. */
  assets?: string;
  getLoadContext?: (args: WorkerLoadContextArgs) => unknown;
  /** A runtime-only config module; `ness.config.mjs` imports Vite. */
  config?: unknown;
  [option: string]: unknown;
}

export interface WorkerConfigOptions {
  name?: string;
  compatibilityDate?: string;
  buildDirectory?: string;
  main?: string;
}

/**
 * Builds a Cloudflare Workers `fetch` handler around a Ness server build.
 *
 * Static files are served by the Workers assets binding rather than by this
 * code: the binding answers from Cloudflare's edge cache without invoking the
 * Worker at all, which is both faster and cheaper than streaming them from JS.
 *
 * Two capabilities do not exist on this runtime and are off by default:
 * on-the-fly image optimization (it needs sharp, a native module) and the
 * filesystem cache adapter. Use Cloudflare Images for the former and a
 * KV- or Durable-Object-backed cache adapter for the latter.
 */
function createWorkerHandler({
  build,
  assets = 'ASSETS',
  getLoadContext,
  config,
  ...handlerOptions
}: WorkerHandlerOptions = {}): {
  fetch(
    request: Request,
    env?: WorkerEnv,
    context?: unknown,
  ): Promise<Response>;
} {
  if (!build) {
    throw new TypeError(
      'createWorkerHandler requires the server build: import * as build from "./build/server/index.js".',
    );
  }

  /**
   * The config is applied lazily, on the first request.
   *
   * Registering a cache adapter or an instrumentation hook at module scope
   * would run during the Worker's startup window, which is metered and short.
   * Doing it on first use also means a Worker with no config pays nothing.
   */
  let ready:
    | Promise<{
        server: Record<string, unknown>;
        handler: (request: Request, context?: unknown) => Promise<Response>;
      }>
    | undefined;
  const prepare = async () => {
    const { server, options } = await applyRuntimeConfig(config);
    return {
      server,
      handler: createNessRequestHandler({
        build: build as ServerBuildLike,
        // sharp is a native module and cannot run on Workers.
        imageHandler: undefined,
        ...options,
        // An explicit option beats the config file, as it does everywhere else.
        ...handlerOptions,
      }),
    };
  };

  return {
    async fetch(request: Request, env?: WorkerEnv, context?: unknown) {
      const binding = env?.[assets] as AssetsBinding | undefined;
      if (binding?.fetch) {
        const asset = await binding.fetch(request);
        if (asset.status !== 404) return asset;
      }

      ready ??= prepare();
      const { handler, server } = await ready;

      // Cloudflare terminates TLS, so the same forwarding rules apply here as
      // behind any other proxy.
      const forwarded = applyForwardedHeaders(request, {
        trustProxy: server['trustProxy'] === true,
      });

      // Workers hand `env` to fetch(), not to module scope, so this is the only
      // place an application can reach its bindings. Default to passing them
      // through: without it a Worker has no way to see KV, D1, or a secret.
      const loadContext = getLoadContext
        ? await getLoadContext({ request: forwarded, env, context })
        : { env, ctx: context };
      return handler(forwarded, loadContext);
    },
  };
}

const WORKER_ENTRY = `// Generated by Ness.js. Edit ness.config.mjs instead.
import * as build from '../server/index.js';
import { createWorkerHandler } from '@nessframework/deployment/cloudflare';

export default createWorkerHandler({ build });
`;

/**
 * The entry, with the runtime config bundled in.
 *
 * A Worker cannot read a file or import a path at runtime, so the config has
 * to be a static import — which is why it points at a runtime-only config
 * rather than at `ness.config.mjs`. That file imports Vite plugins at module
 * scope, and importing it here would pull the whole build toolchain into the
 * Worker.
 */
function workerEntry({
  configPath,
}: { configPath?: string | undefined } = {}): string {
  if (!configPath) return WORKER_ENTRY;
  return `// Generated by Ness.js. Edit ${configPath.split('/').pop()} instead.
import * as build from '../server/index.js';
import config from '${configPath}';
import { createWorkerHandler } from '@nessframework/deployment/cloudflare';

export default createWorkerHandler({ build, config });
`;
}

/**
 * Emits the Worker entry and a wrangler configuration that match the build
 * output layout. `nodejs_compat` is required: the framework uses
 * node:async_hooks for request-scoped caching and node:crypto for cache keys.
 */
function createWorkerConfig({
  name = 'ness-app',
  compatibilityDate = '2025-01-01',
  buildDirectory = 'build',
  main = `${buildDirectory}/worker/index.js`,
}: WorkerConfigOptions = {}): Record<string, unknown> {
  return {
    name,
    main,
    compatibility_date: compatibilityDate,
    compatibility_flags: ['nodejs_compat'],
    assets: {
      directory: `${buildDirectory}/client`,
      binding: 'ASSETS',
      // The Worker owns routing; the binding only answers for files it has.
      not_found_handling: 'none',
    },
    observability: { enabled: true },
  };
}

export { WORKER_ENTRY, createWorkerConfig, createWorkerHandler, workerEntry };
export default createWorkerHandler;
