import fs from 'node:fs';
import path from 'node:path';
import { readManifest, traceDependencies } from './trace.js';

const LAUNCHER = `#!/usr/bin/env node
// Generated by Ness.js. Starts the standalone server with no npm install step.

// React and react-dom each pick their development or production build when
// they are first required. This must be set before anything imports them, or
// a development React is paired with a production react-dom and rendering
// fails with "dispatcher.getOwner is not a function".
process.env.NODE_ENV = process.env.NODE_ENV || 'production';

const { createRequire } = await import('node:module');
const path = (await import('node:path')).default;
const { fileURLToPath, pathToFileURL } = await import('node:url');

const here = path.dirname(fileURLToPath(import.meta.url));
process.chdir(here);

const require = createRequire(import.meta.url);
const core = path.dirname(require.resolve('@nessframework/core/package.json'));
process.argv[2] =
  process.argv[2] || path.join(here, 'build', 'server', 'index.js');

await import(pathToFileURL(path.join(core, 'src', 'bin', 'serve.js')).href);
`;

function copyDirectory(source, destination, { filter } = {}) {
  fs.mkdirSync(destination, { recursive: true });
  for (const entry of fs.readdirSync(source, { withFileTypes: true })) {
    const from = path.join(source, entry.name);
    const to = path.join(destination, entry.name);
    if (filter && !filter(from, entry)) continue;
    if (entry.isDirectory()) {
      copyDirectory(from, to, { filter });
    } else if (entry.isSymbolicLink()) {
      // Recreating the link verbatim leaves it dangling whenever the target
      // lies outside the copied tree — which is every link under a pnpm
      // install, where node_modules is a farm of links into a store. Copy what
      // the link points at instead.
      const resolved = (() => {
        try {
          return fs.statSync(from);
        } catch {
          return undefined;
        }
      })();
      if (!resolved) continue;
      if (resolved.isDirectory())
        copyDirectory(fs.realpathSync(from), to, { filter });
      else fs.copyFileSync(from, to);
    } else {
      fs.copyFileSync(from, to);
    }
  }
}

function directorySize(directory) {
  let total = 0;
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    const target = path.join(directory, entry.name);
    if (entry.isDirectory()) total += directorySize(target);
    else if (entry.isFile()) {
      try {
        total += fs.statSync(target).size;
      } catch {
        // A file can vanish between the listing and the stat; size is a report,
        // not a correctness signal.
      }
    }
  }
  return total;
}

const SKIPPED_PACKAGE_ENTRIES = new Set([
  '.bin',
  '.github',
  '__tests__',
  'test',
  'tests',
  'example',
  'examples',
  'docs',
  'coverage',
  'CHANGELOG.md',
]);

/**
 * Produces a self-contained deployment directory: the build output, the public
 * assets, a traced production `node_modules`, and a launcher. The result runs
 * with `node build/standalone/server.mjs` on a bare Node image — no npm
 * install, no lockfile, no registry access at deploy time.
 */
async function createStandaloneOutput({
  root = process.cwd(),
  buildDirectory = 'build',
  outputDirectory = path.join(buildDirectory, 'standalone'),
  publicDirectory = 'public',
  includeDevDependencies = false,
  extraPackages = [],
  logger = console,
} = {}) {
  const absoluteRoot = path.resolve(root);
  const absoluteBuild = path.resolve(absoluteRoot, buildDirectory);
  const output = path.resolve(absoluteRoot, outputDirectory);

  if (!fs.existsSync(absoluteBuild)) {
    throw new Error(
      `No build output at ${absoluteBuild}. Run \`ness build\` before bundling.`,
    );
  }
  const serverEntry = path.join(absoluteBuild, 'server', 'index.js');
  if (!fs.existsSync(serverEntry)) {
    throw new Error(`No server build at ${serverEntry}.`);
  }

  const manifest = readManifest(absoluteRoot);
  if (!manifest) throw new Error(`No package.json found in ${absoluteRoot}`);

  // The output directory is wiped, and it comes from the caller (`--output`).
  // `path.resolve(root, '.')` is the project itself and '..' is worse, so
  // refuse anything that is the project or contains it before deleting.
  const relativeToRoot = path.relative(output, absoluteRoot);
  if (
    output === absoluteRoot ||
    relativeToRoot === '' ||
    (!relativeToRoot.startsWith('..') && !path.isAbsolute(relativeToRoot))
  ) {
    throw new Error(
      `Refusing to write the standalone bundle to ${output}: it is the project directory or contains it, and the bundle directory is emptied before it is written.`,
    );
  }

  fs.rmSync(output, { recursive: true, force: true });
  fs.mkdirSync(output, { recursive: true });

  // The build output, minus the standalone directory itself.
  copyDirectory(absoluteBuild, path.join(output, 'build'), {
    filter: from => path.resolve(from) !== output,
  });

  const publicSource = path.resolve(absoluteRoot, publicDirectory);
  if (fs.existsSync(publicSource)) {
    copyDirectory(publicSource, path.join(output, 'public'));
  }

  for (const configFile of [
    'ness.config.mjs',
    'ness.config.js',
    'instrumentation.mjs',
    'instrumentation.js',
  ]) {
    const source = path.join(absoluteRoot, configFile);
    if (fs.existsSync(source)) {
      fs.copyFileSync(source, path.join(output, configFile));
    }
  }

  const { packages, conflicts, missing } = traceDependencies(absoluteRoot, {
    manifest: includeDevDependencies
      ? {
          ...manifest,
          dependencies: {
            ...manifest.dependencies,
            ...manifest.devDependencies,
          },
        }
      : manifest,
    extra: extraPackages,
  });

  const modulesDirectory = path.join(output, 'node_modules');
  const packageFilter = (_from, entry) =>
    !SKIPPED_PACKAGE_ENTRIES.has(entry.name) && entry.name !== 'node_modules';

  for (const [name, directory] of packages) {
    copyDirectory(directory, path.join(modulesDirectory, name), {
      filter: packageFilter,
    });
  }

  // A second version of a name cannot share the top level, so it is nested
  // under the package that asked for it — exactly where Node's resolver looks.
  for (const { name, directory, requiredBy } of conflicts) {
    if (!packages.has(requiredBy)) continue;
    copyDirectory(
      directory,
      path.join(modulesDirectory, requiredBy, 'node_modules', name),
      { filter: packageFilter },
    );
  }

  fs.writeFileSync(path.join(output, 'server.mjs'), LAUNCHER);
  fs.writeFileSync(
    path.join(output, 'package.json'),
    `${JSON.stringify(
      {
        name: `${manifest.name || 'ness-app'}-standalone`,
        version: manifest.version || '0.0.0',
        private: true,
        type: 'module',
        scripts: { start: 'node server.mjs' },
      },
      null,
      2,
    )}\n`,
  );

  const size = directorySize(output);
  const report = {
    output,
    packages: packages.size,
    missing,
    bytes: size,
  };

  logger?.log?.(
    `Standalone output: ${output}\n  ${packages.size} packages, ${(size / 1_048_576).toFixed(1)} MB`,
  );
  if (missing.length) {
    logger?.warn?.(
      `  ${missing.length} dependency/dependencies could not be resolved and were skipped: ${missing.join(', ')}`,
    );
  }
  return report;
}

export { createStandaloneOutput };
export default createStandaloneOutput;
