import fs from 'node:fs';
import path from 'node:path';
import { readManifest, traceDependencies } from './trace.js';

/**
 * Builds an Express-compatible `(req, res)` handler around a Ness server
 * build, for Vercel's Node.js Function runtime.
 *
 * Unlike `createLambdaApplication`/`createWorkerHandler`, this composes
 * `configureServer` — the same hook `packages/core/src/bin/serve.js` calls —
 * so a plugin like `@nessframework/nest` gets to mount its own middleware
 * (an Express sub-app) ahead of the SSR fallback. Vercel's Node runtime is a
 * real Node process, unlike Cloudflare Workers' isolate, so there is nowhere
 * near the same pressure to avoid Express; and unlike raw Lambda, there is
 * no API-Gateway-shaped event to convert from — Vercel's Node Functions
 * already accept a plain `(req, res)` handler or an Express app directly.
 *
 * Imports inside `prepare()` are lazy, matching `createLambdaApplication`:
 * a cold start is metered, and a Function that never actually gets a request
 * (rare, but happens during a deploy's health check) should not pay for
 * `express`, the cache adapter, or instrumentation setup at all.
 */
function createVercelHandler({ build, config, root, ...handlerOptions } = {}) {
  if (!build) {
    throw new TypeError(
      'createVercelHandler requires the server build: import * as build from "./build/server/index.js".',
    );
  }
  const resolvedRoot = root || process.cwd();

  let ready;
  const prepare = async () => {
    const { createNessRequestHandler } = await import('@nessframework/server');
    const { applyForwardedHeaders } =
      await import('@nessframework/server/proxy');
    const { compressResponse } = await import('@nessframework/server/compress');
    const { applyRuntimeConfig } =
      await import('@nessframework/server/runtime');
    const { createImageHandler } =
      await import('@nessframework/assets/image/server');
    const { createRequestListener } =
      await import('@remix-run/node-fetch-server');
    const { default: express } = await import('express');

    const { server, options } = await applyRuntimeConfig(config);
    const imageHandler =
      server.images === false
        ? undefined
        : createImageHandler(
            typeof server.images === 'object' ? server.images : {},
          );
    const handler = createNessRequestHandler({
      build,
      imageHandler,
      ...options,
      ...handlerOptions,
    });

    const app = express();
    app.disable('x-powered-by');

    // The Nest (or any other plugin's) middleware, mounted ahead of the SSR
    // fallback — same contract, same order, as `serve.js`.
    const disposeConfiguredServer = server.configureServer
      ? await server.configureServer(app, {
          root: resolvedRoot,
          build,
          handler,
        })
      : undefined;

    const compressionOptions =
      typeof server.compression === 'object' ? server.compression : {};
    const respond = async incoming => {
      const request = applyForwardedHeaders(incoming, {
        // Vercel terminates TLS and forwards the original scheme, same as
        // API Gateway in front of Lambda.
        trustProxy: server.trustProxy === true,
      });
      const response = await handler(request);
      return server.compression === false
        ? response
        : compressResponse(request, response, compressionOptions);
    };
    app.use(createRequestListener(respond));

    return { app, disposeConfiguredServer };
  };

  return async function vercel(request, response) {
    ready ??= prepare();
    const { app } = await ready;
    return app(request, response);
  };
}

const VERCEL_ENTRY = `// Generated by Ness.js. Edit ness.server.config.mjs instead.
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as build from './build/server/index.js';
import { createVercelHandler } from '@nessframework/deployment/vercel';

const root = path.dirname(fileURLToPath(import.meta.url));

export default createVercelHandler({ build, root });
`;

/**
 * The generated Vercel Function entry, with the runtime config bundled in
 * when there is one — same reasoning as \`workerEntry\`: \`ness.config.mjs\`
 * imports Vite plugins at module scope, which a deployed function cannot
 * carry, so a runtime-only config file is imported instead when present.
 *
 * The config is a namespace import (\`import * as config\`), not a default
 * import: `serverConfig()` (`@nessframework/server/runtime`) is written to
 * accept either shape (`config?.default ?? config`, falling back to the
 * whole module when there is no default export) — but that fallback only
 * runs if the import itself succeeds. A runtime config file that only has
 * named exports (`export const server = ...`, matching this project's own
 * convention, and `serve.js`'s own loader, which tries `module.default`
 * before falling back to `module`) has no default export at all, so
 * `import config from '...'` fails to *link* — a SyntaxError before
 * `serverConfig`'s leniency ever gets a chance to run.
 */
function vercelEntry({ configPath } = {}) {
  if (!configPath) return VERCEL_ENTRY;
  return `// Generated by Ness.js. Edit ${configPath.split('/').pop()} instead.
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as build from './build/server/index.js';
import * as config from '${configPath}';
import { createVercelHandler } from '@nessframework/deployment/vercel';

const root = path.dirname(fileURLToPath(import.meta.url));

export default createVercelHandler({ build, root, config });
`;
}

function copyDirectory(source, destination, { filter } = {}) {
  fs.mkdirSync(destination, { recursive: true });
  for (const entry of fs.readdirSync(source, { withFileTypes: true })) {
    const from = path.join(source, entry.name);
    const to = path.join(destination, entry.name);
    if (filter && !filter(from, entry)) continue;
    if (entry.isDirectory()) {
      copyDirectory(from, to, { filter });
    } else if (entry.isSymbolicLink()) {
      // Same reasoning as `standalone.js`: recreating the link verbatim
      // leaves it dangling once its target is outside the copied tree,
      // which is the normal case for a pnpm-style node_modules.
      const resolved = (() => {
        try {
          return fs.statSync(from);
        } catch {
          return undefined;
        }
      })();
      if (!resolved) continue;
      if (resolved.isDirectory())
        copyDirectory(fs.realpathSync(from), to, { filter });
      else fs.copyFileSync(from, to);
    } else {
      fs.copyFileSync(from, to);
    }
  }
}

function directorySize(directory) {
  let total = 0;
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    const target = path.join(directory, entry.name);
    if (entry.isDirectory()) total += directorySize(target);
    else if (entry.isFile()) {
      try {
        total += fs.statSync(target).size;
      } catch {
        // A file can vanish between the listing and the stat; size is a
        // report, not a correctness signal.
      }
    }
  }
  return total;
}

const SKIPPED_PACKAGE_ENTRIES = new Set([
  '.bin',
  '.github',
  '__tests__',
  'test',
  'tests',
  'example',
  'examples',
  'docs',
  'coverage',
  'CHANGELOG.md',
]);

/**
 * Emits a Vercel Build Output API v3 deployment: a Node.js Function directory
 * (`.vercel/output/functions/index.func`) with a traced production
 * `node_modules`, the server and (optional) Nest build output, and a
 * generated entry point; the client build as static files
 * (`.vercel/output/static`); and routing config that serves a static file
 * when one matches and falls through to the function otherwise.
 *
 * This exists instead of relying on `vercel.json`'s `functions.*.includeFiles`
 * plus Vercel's own dependency tracer (`@vercel/nft`) because that tracer
 * walks the *JS import graph* from the function's entry file — and
 * `nestServer()` loads `build/nest/app.module.js` through a runtime-computed
 * path (it has to: it is generic across every Ness.js app), which no static
 * analysis can follow. Every package reachable only through the Nest app
 * graph — not also imported by the entry file itself — was invisible to it,
 * one crash per deploy as each code path was hit for the first time.
 * `traceDependencies` walks `package.json` manifests instead of JS imports,
 * so it is unaffected by how anything actually gets loaded at runtime: a
 * declared `dependencies` entry ships, full stop. And because this writes
 * `.vercel/output` directly, Vercel does no tracing or size-limiting glob
 * matching of its own — there is nothing to hit a schema length limit on.
 */
async function createVercelOutput({
  root = process.cwd(),
  buildDirectory = 'build',
  outputDirectory = '.vercel/output',
  configPath,
  runtime = 'nodejs22.x',
  extraPackages = [],
  logger = console,
} = {}) {
  const absoluteRoot = path.resolve(root);
  const absoluteBuild = path.resolve(absoluteRoot, buildDirectory);
  const output = path.resolve(absoluteRoot, outputDirectory);

  const serverEntry = path.join(absoluteBuild, 'server', 'index.js');
  if (!fs.existsSync(serverEntry)) {
    throw new Error(`No server build at ${serverEntry}. Run \`ness build\` before bundling.`);
  }

  const manifest = readManifest(absoluteRoot);
  if (!manifest) throw new Error(`No package.json found in ${absoluteRoot}`);

  fs.rmSync(output, { recursive: true, force: true });

  const functionDirectory = path.join(
    output,
    'functions',
    'index.func',
  );
  const functionBuildDirectory = path.join(functionDirectory, 'build');
  fs.mkdirSync(functionBuildDirectory, { recursive: true });

  copyDirectory(
    path.join(absoluteBuild, 'server'),
    path.join(functionBuildDirectory, 'server'),
  );

  const nestBuild = path.join(absoluteBuild, 'nest');
  if (fs.existsSync(nestBuild)) {
    copyDirectory(nestBuild, path.join(functionBuildDirectory, 'nest'));
  }

  const resolvedConfigPath =
    configPath ||
    ['ness.server.config.mjs', 'ness.server.config.js']
      .find(candidate => fs.existsSync(path.join(absoluteRoot, candidate)));
  if (resolvedConfigPath) {
    fs.copyFileSync(
      path.join(absoluteRoot, resolvedConfigPath),
      path.join(functionDirectory, resolvedConfigPath),
    );
  }

  fs.writeFileSync(
    path.join(functionDirectory, 'index.js'),
    vercelEntry({ configPath: resolvedConfigPath ? `./${resolvedConfigPath}` : undefined }),
  );
  fs.writeFileSync(
    path.join(functionDirectory, '.vc-config.json'),
    `${JSON.stringify(
      { runtime, handler: 'index.js', launcherType: 'Nodejs' },
      null,
      2,
    )}\n`,
  );
  // Without this, Node has no package.json above `index.js` inside the
  // deployed function root (/var/task) to learn its module system from, and
  // falls back to CommonJS — which chokes on the entry's own `import`
  // statements before anything of ours ever runs. Same reason
  // `createStandaloneOutput` writes one of its own.
  fs.writeFileSync(
    path.join(functionDirectory, 'package.json'),
    `${JSON.stringify(
      { name: `${manifest.name || 'ness-app'}-vercel`, private: true, type: 'module' },
      null,
      2,
    )}\n`,
  );

  const { packages, conflicts, missing } = traceDependencies(absoluteRoot, {
    manifest,
    extra: extraPackages,
  });

  const modulesDirectory = path.join(functionDirectory, 'node_modules');
  const packageFilter = (_from, entry) =>
    !SKIPPED_PACKAGE_ENTRIES.has(entry.name) && entry.name !== 'node_modules';

  for (const [name, directory] of packages) {
    copyDirectory(directory, path.join(modulesDirectory, name), {
      filter: packageFilter,
    });
  }
  // `requiredBy` may itself be a nested destination (e.g.
  // `multer/node_modules/type-is`, when the package doing the requiring is
  // itself a conflict, not a top-level winner) — only its own top-level
  // ancestor needs to actually exist for the nesting to be valid.
  for (const { name, directory, requiredBy } of conflicts) {
    const topLevelAncestor = requiredBy.split('/node_modules/')[0];
    if (!packages.has(topLevelAncestor)) continue;
    copyDirectory(
      directory,
      path.join(modulesDirectory, requiredBy, 'node_modules', name),
      { filter: packageFilter },
    );
  }

  const clientBuild = path.join(absoluteBuild, 'client');
  if (fs.existsSync(clientBuild)) {
    copyDirectory(clientBuild, path.join(output, 'static'));
  }

  fs.writeFileSync(
    path.join(output, 'config.json'),
    `${JSON.stringify(
      {
        version: 3,
        routes: [
          { handle: 'filesystem' },
          { src: '/(.*)', dest: '/index' },
        ],
      },
      null,
      2,
    )}\n`,
  );

  const size = directorySize(functionDirectory);
  const report = {
    output,
    function: functionDirectory,
    packages: packages.size,
    missing,
    bytes: size,
  };

  logger?.log?.(
    `Vercel Build Output: ${output}\n  ${packages.size} packages, ${(size / 1_048_576).toFixed(1)} MB (function)`,
  );
  if (missing.length) {
    logger?.warn?.(
      `  ${missing.length} dependency/dependencies could not be resolved and were skipped: ${missing.join(', ')}`,
    );
  }
  return report;
}

export { createVercelHandler, createVercelOutput, VERCEL_ENTRY, vercelEntry };
export default createVercelHandler;
